// 中英數通 ＝ hkdselibrary@gmail.com
// 其他 ＝alexsze0128@gmail.com
// tszwaiwong112@gmail.com
// leewaifungtim@gmail.com

module.exports = [{
    title: '上載區',
    years: ['Upload'],
    lang: 'EN',
    url: 'https://drive.google.com/drive/folders/1wNOYL7alpLvQCPh0hoAdruWFWrTGcg7T?usp=sharing'
},
{
    title: '中國語文',
    lang: 'ZH',
    years: ['One Click', '樣本試卷', '練習試卷', '樣本試卷 2018', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 'CE'],
    url: ['https://drive.google.com/drive/folders/1A1bIEkOQxtobs-lXbC1yQEtgnwtr2Sqx?usp=sharing',
        'https://drive.google.com/drive/folders/11ZvV83CeGP86KkvUQk2MAaqjnI9GtRwc?usp=sharing',
        'https://drive.google.com/drive/folders/1oXd1VRCumoLG5V6KPImPCoDH9Zm13OT0?usp=sharing',
        'https://drive.google.com/drive/folders/1mqupNd1qK_So5IQjuz_3b4ZJU3QhrZDU?usp=sharing',
        'https://drive.google.com/drive/folders/14qFgR5Bupk9CU_mWOJwsyJWc7hwsTY6K?usp=sharing',
        'https://drive.google.com/drive/folders/1hhOe0zoKtZIAdQKcFlBfKq96vKGMRVyS?usp=sharing',
        'https://drive.google.com/drive/folders/1WbRG1ICSVsDJfTAzh-UIRMKdZmMvfeQh?usp=sharing',
        'https://drive.google.com/drive/folders/1r0_xHijNV_jbFG0VeXucqi_ieTrT1vnn?usp=sharing',
        'https://drive.google.com/drive/folders/1W0zqU93-CIqW3MrPyFP-9Azg7ahP01LK?usp=sharing',
        'https://drive.google.com/drive/folders/1ZX21gwSrX2YZk3RXOAHyXJuHocV8lNG5?usp=sharing',
        'https://drive.google.com/drive/folders/1JPXN-H6thWjVPx0_28Px-yzB0nTI--O_?usp=sharing',
        'https://drive.google.com/drive/folders/1Bl9y_0AcOh--Jfk2lr5pL1ZDo2_NEJFz?usp=sharing',
        'https://drive.google.com/drive/folders/1kXt__saSPlQ2bXdPubxtJSs6pA6_sk5a?usp=share_link',
        'https://drive.google.com/drive/folders/1tehJrRf_pdALcYcM4Qh0I6ByuBbiT-eZ?usp=share_link',
        'https://drive.google.com/drive/folders/1Aby6yW4aWLgklVAw4NtIXoLABvsMQJst?usp=share_link',
        'https://drive.google.com/drive/folders/1HRV00LkOp_ZDVXxCwiUeWQhrdRub1SlF?usp=sharing'
    ]
},
{
    title: 'English',
    lang: 'EN',
    years: ['One Click', 'Sample Paper', 'Practice Paper', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 'CE', 'AL'],
    url: ['https://drive.google.com/drive/folders/1oWXDvG4FbSoW_nP88R73TKqQivYmzZ1Y?usp=sharing',
        'https://drive.google.com/drive/folders/1sWMNDPDj62gtagMBHsLznLMTHWizemmV?usp=sharing',
        'https://drive.google.com/drive/folders/1o_XSYsA4RwkyCJv1-1HJAGQRjKoHwmAW?usp=sharing',
        'https://drive.google.com/drive/folders/162RtBk0EuPcD2sitLvdsoCevjXZjoHFM?usp=sharing',
        'https://drive.google.com/drive/folders/1OFMbygGpxhCPOdjwLt0BW18USU7nO-Q8?usp=sharing',
        'https://drive.google.com/drive/folders/1c__E8NItELEATAR5SdVhTh5PgsGUBgmF?usp=sharing',
        'https://drive.google.com/drive/folders/11HfwhSnGQgcYOiIgdjzh4E71GNdQS0cv?usp=sharing',
        'https://drive.google.com/drive/folders/1IRfkoBa0gmD9PyR7i8ro5yv5AMelVzoh?usp=sharing',
        'https://drive.google.com/drive/folders/1mpGkm-bbZHiC8myMvXlRo3rm5vS1-UU8?usp=sharing',
        'https://drive.google.com/drive/folders/1c8WmZppKzDRyQK9-Yw6OOSDlbmbD_Gp6?usp=sharing',
        'https://drive.google.com/drive/folders/1ora7Vqafy9OBRdwqEHhwiF4oGe7_BFUa?usp=sharing',
        'https://drive.google.com/drive/folders/1Bbk2NVx0RKC1ya5noZn8IAHu-NnUQGqV?usp=sharing',
        'https://drive.google.com/drive/folders/1Wmap0S5ayUrowvRwb9PzCLCi3ZlIU03a?usp=sharing',
        'https://drive.google.com/drive/folders/1qCYfJJdKsS4HvyGUWYB6U7nOwVprvoUO?usp=share_link',
        'https://drive.google.com/drive/folders/1HfhKlxx-eOqLASuZ34FsPZ2bn5rOdsUj',
        'https://drive.google.com/drive/folders/112bnI6KMK_L6zIfGdMckQpW8ZOdfYvjz?usp=sharing'

    ]
},
{
    title: 'Mathematic',
    lang: 'EN',
    years: ['One Click', 'Sample Paper', 'Practice Paper', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/13EtyNpaRyFRxdVCI5P5HE6WnHVGY9xIJ?usp=sharing',
        'https://drive.google.com/drive/folders/13L96p6FEEaRaX7LpMaBPGl_FfpPIcK98?usp=sharing',
        'https://drive.google.com/drive/folders/1QC7gNjNv4R8EsVDwBCTogxficdkU-aad?usp=sharing',
        'https://drive.google.com/drive/folders/1x9axyIWqq9dFHu4WjIMx80VWra28YWh0?usp=sharing',
        'https://drive.google.com/drive/folders/1ocgi3v1Wc-7YeOkJ0nkhp6jn8ig8kuax?usp=sharing',
        'https://drive.google.com/drive/folders/1qXnPxIF6DDX78SSqIqf7a0mrw3p_L9Ov?usp=sharing',
        'https://drive.google.com/drive/folders/1lLVPvC5wjZAAfmWHfGLU4biQcp72ztR7?usp=sharing',
        'https://drive.google.com/drive/folders/1iawYeK_Ojf89q8K3FaFYqZdz4QOVXLJj?usp=sharing',
        'https://drive.google.com/drive/folders/1O1dzraOawrDNcycqz_aRJKodP9Oad0o-?usp=sharing',
        'https://drive.google.com/drive/folders/1D27CIQm2-tonQ_yNXwR_GG0OQ3sMdjKD?usp=sharing',
        'https://drive.google.com/drive/folders/1l5IlfvvzfiRTXvfkzs114zkfCuAHgB3n?usp=sharing',
        'https://drive.google.com/drive/folders/1b6UwbO-YLSE15MqKJOXIivBxYjjNvwzx?usp=sharing',
        'https://drive.google.com/drive/folders/1A1iSo23tTd9fmQ55FIFUBQA9cUewOot9?usp=share_link',
        'https://drive.google.com/drive/folders/1sW-SkRpYnXXosBYkBGsqE1rsNkXgP4e-?usp=share_link',

    ]
},
{
    title: '數學',
    lang: 'ZH',
    years: ['One Click', '樣本試卷', '練習試卷', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/1-GaDc_AZdjEk-DpcFZxtbzcwilVTfkb_?usp=sharing',
        'https://drive.google.com/drive/folders/10HjpTVYerLsrgOydvcS5urRmwX21M6uO?usp=sharing',
        'https://drive.google.com/drive/folders/10e9DrjCegYjAjbsS-ceYvuQ382YPDO3X?usp=sharing',
        'https://drive.google.com/drive/folders/10Az5I_fiOQ_xOOCstTAuRsXUBZpgAJ3D?usp=sharing',
        'https://drive.google.com/drive/folders/10IXbUQKkdp0ldmBkxXZHuXDaHDxyYbu-?usp=sharing',
        'https://drive.google.com/drive/folders/10OOS1mQkPbsfXyV5FN0-lqNmSzDtz_TH?usp=sharing',
        'https://drive.google.com/drive/folders/10WDMeKVDNl3zjZ9dLK51ttMITKi5WGo_?usp=sharing',
        'https://drive.google.com/drive/folders/10Z3-ucoKy05nImWmSB8idNJsvzzBMZon?usp=sharing',
        'https://drive.google.com/drive/folders/10BTDblKsYuXNO1bf3iUO5ExnUw06N2H6?usp=sharing',
        'https://drive.google.com/drive/folders/1bch69Ek1QurJ0k2zEtDZrKEumk-i21Qc?usp=share_link',
        'https://drive.google.com/drive/folders/1UsXYVV0J7nFhBe2KcH1zSL-z_3fN-wmM?usp=share_link',
        'https://drive.google.com/drive/folders/115DXb9-2TkBdJc_3W-rDI9Kl1no4iGEw?usp=share_link',
        'https://drive.google.com/drive/folders/1yLstGHWeqQWxVzpw_aR_4NT8_9AwevKL?usp=share_link',
        'https://drive.google.com/drive/folders/145l_VEbC44aj99Q3VwICw1gnxRohy-Oc?usp=share_link',
    ]
},
{
    title: '通識',
    lang: 'ZH',
    years: ['One Click', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/1RO70hJe1k9ZjgknE677NSVCIzvgvYF--?usp=sharing',
        'https://drive.google.com/drive/folders/1zHCoJnITcO6lvcy2_XUcX9Zt2dSKFvdW?usp=sharing',
        'https://drive.google.com/drive/folders/1HPB9xiWPD-2SJ8EVKqWovFmobxLqZkvl?usp=sharing',
        'https://drive.google.com/drive/folders/1StrivdH4Pnuk68JTRrXfKnIlK5Xr7QzX?usp=sharing',
        'https://drive.google.com/drive/folders/1GLefpmAIv5qCw9uaMY_vw3FW1E1JaLx9?usp=sharing',
        'https://drive.google.com/drive/folders/1cKd5huyEP9n_9yE2NtEb4GkAoadEcHAk?usp=sharing',
        'https://drive.google.com/drive/folders/1lG-Jdwxj7AkZKo66MIH47VB2zhY4zJ9d?usp=sharing',
        'https://drive.google.com/drive/folders/1jMyBcds_PtL-cU4pPOnthqk-oTWH9-wL?usp=sharing',
        'https://drive.google.com/drive/folders/1Q543jNl6LecFcg0t0C5iDHjWqk8gKy4Y?usp=sharing',
        'https://drive.google.com/drive/folders/1QDpjJqPqNsNUuqC0Qd2zhxCSvW2Zgd-c?usp=share_link',
        'https://drive.google.com/drive/folders/10LoIG-gWC9znVRWLyF_O2SQogeoDr6eV?usp=share_link',
        'https://drive.google.com/drive/folders/1but4Spr7kpSglXb2x8By_6umjn4RbQRl?usp=share_link',
    ]
},
{
    title: 'Physic',
    lang: 'EN',
    years: ['One Click', 'Sample Paper', 'Practice Paper', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/1mXZ90INAMPZ2Rn7OkemS8LwxpFamqWkr?usp=sharing',
        'https://drive.google.com/drive/folders/1in7AGv4jNEVlGCdtu8yQSV1gMKtk6pGn?usp=share_link',
        'https://drive.google.com/drive/folders/1ea_I_d3mMgjEv_RquE7n4yUGzzLLADKI?usp=share_link',
        'https://drive.google.com/drive/folders/12ZQb2D3qHR1cFQkJ_CL4xeUXaCeIdqKV?usp=sharing',
        'https://drive.google.com/drive/folders/1u2Lk5UlLRQkaqALNjLycsFXMIBN-1Krj?usp=sharing',
        'https://drive.google.com/drive/folders/1C4qUeiqYaOfWrihrHHavWRNSfl3ewq8U?usp=sharing',
        'https://drive.google.com/drive/folders/1_3tlu9FfJIWkwBfmuaJIOvrzi_CmirRQ?usp=sharing',
        'https://drive.google.com/drive/folders/1baMPkQ0qMQHKWGZSywAlRcbGPsAVo2B_?usp=sharing',
        'https://drive.google.com/drive/folders/14yAy1by8KkYsK04wxArc8rkbS0dv_Tsl?usp=sharing',
        'https://drive.google.com/drive/folders/1dVeVU435CMLCfh8cOvfUNlolRj33hjO7?usp=sharing',
        'https://drive.google.com/drive/folders/1ED7fZkEGFQty2cnzst-C7LclakVp-Z3k?usp=sharing',
        'https://drive.google.com/drive/folders/1aryWkZHfCKbuIyMl_tvHbYxteoHSHC4W?usp=sharing',
        'https://drive.google.com/drive/folders/1zvwnFHe2mHk5RZ288XpKLv4b4ZjocZto?usp=sharing',
        'https://drive.google.com/drive/folders/1hqxd6le-dHzGa_6OSNM8Bia_pUJn2RFa?usp=share_link',
    ]
},
{
    title: '物理',
    lang: 'ZH',
    years: ['One Click', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/1bfpER1VXnf0B66ySSmWdkGCrygH2rb_D?usp=sharing',
        'https://drive.google.com/drive/folders/1h7ClSs6usH5meToS3Tpyf5EKRmyUg_AI?usp=sharing',
        'https://drive.google.com/drive/folders/1KIvSaH2tiUN8L6Jid1VWA9KUXCfvg_aE?usp=sharing',
        'https://drive.google.com/drive/folders/1vcwv8gXt7-BVFzJEDL7ZtpUsCrvBwDEO?usp=sharing',
        'https://drive.google.com/drive/folders/1ru15CB5jpoQsNu-I6Mdd54VTpBokJAVm?usp=sharing',
        'https://drive.google.com/drive/folders/1vAnicR0HY2ZPhw6RNbhX7rdzQtoDcKeP?usp=sharing',
        'https://drive.google.com/drive/folders/1xeoRZyh6_K0vnsjXH_3_bj6lJFJZ_9Dl?usp=sharing',
        'https://drive.google.com/drive/folders/1jtmmmH0HGL-Hh5ehYgJDB5BHedA9ZTpN?usp=share_link',
        'https://drive.google.com/drive/folders/11gLqq35CvD_-8ME-wFnBX9KkY1UYgGBH?usp=share_link',
        'https://drive.google.com/drive/folders/1wdqSKnD6U1pwtNb52DtjZw7AMnHYmAsN?usp=share_link',
        'https://drive.google.com/drive/folders/1khQo0t2Y5B0gprAB_9wjfZNlwg7X93z9?usp=share_link',
        'https://drive.google.com/drive/folders/1CUTAx0m6Suw80OppQ6yR9zL5HUr2TtQN?usp=share_link',
    ]
},
{
    title: 'Chemistry',
    lang: 'EN',
    years: ['One Click', 'Sample Paper', 'Practice Paper', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/1cy2AU6ThKpB0-Gt4oJAC6YVe8z9Opjsx?usp=sharing',
        'https://drive.google.com/drive/folders/1K8PS_f7lQvwU9caD8JiTQxHr90kWg4M2?usp=share_link',
        'https://drive.google.com/drive/folders/1UcLDF_uGydybM0vua30NxTaV8rpfxkfK?usp=share_link',
        'https://drive.google.com/drive/folders/17hRio3QMO8A0_AwUOmkttlS2hoCE4XoK?usp=sharing',
        'https://drive.google.com/drive/folders/1ysBA5C78DteaT_npeeHMk4SLOvH-AoEk?usp=sharing',
        'https://drive.google.com/drive/folders/1VulkaS6OswwB4Q2A9bWUOm_p8t13o2JD?usp=sharing',
        'https://drive.google.com/drive/folders/11EOOLLS-plzOe7_gLBfLz9XZOGzfBgVZ?usp=sharing',
        'https://drive.google.com/drive/folders/1r27x2b23GwfcoAMtfR7n_gQbZu6JosyV?usp=sharing',
        'https://drive.google.com/drive/folders/1fO5eay2OQVZyUTw9uF86zSa5wwaejdlZ?usp=sharing',
        'https://drive.google.com/drive/folders/1Po4l66gKlJv0cT_isMbrzKQqNdIFqA_s?usp=sharing',
        'https://drive.google.com/drive/folders/1LujckjmFSQOv2E3ZLRLxJG_XtwbfQYCv?usp=sharing',
        'https://drive.google.com/drive/folders/18LQkaGqfiMd7mg9hTYS6Qvw-iVFSTYt8?usp=share_link',
        'https://drive.google.com/drive/folders/1xVXaFLHe_V1xVoCdOerhya_t1ecK9n6v?usp=sharing',
        'https://drive.google.com/drive/folders/1Gd8_78xMSnCja4zYnPqYGQx_Zb5YUenF?usp=share_link',
    ]
},
{
    title: 'DSE00 Mocks',
    lang: 'EN',
    years: ['One Click', 2017, 2019, 2020],
    url: ['https://drive.google.com/drive/folders/1ElNJ0BMlqw_0AOvwTZiykgTizI4GFjdF?usp=sharing',
        'https://drive.google.com/drive/folders/1OI5aIFflWt0pnhdoxd_u47_O63RH3gBD?usp=sharing',
        'https://drive.google.com/drive/folders/1ihe4FzX3-f-DSfgJgBECjt8kevHBsMOR?usp=sharing',
        'https://drive.google.com/drive/folders/1PRv0M4XJwQNaab3KaCAfBz05K06pNIgT?usp=sharing'
    ]
},

{
    title: '化學',
    lang: 'ZH',
    years: ['One Click', '樣本試卷', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021],
    url: ['https://drive.google.com/drive/folders/15A6dGceedIWQXCXiqJNkSjcfnwtiqEDd?usp=sharing',
        'https://drive.google.com/drive/folders/1i3ftCpZvSHtXf384avZo7ZZqCvKbdR1p?usp=sharing',
        'https://drive.google.com/drive/folders/1k0w4HEGWYp_-s6qLJ69tRmEFRu-FZJmo?usp=sharing',
        'https://drive.google.com/drive/folders/1ANXd5dUiuSnQcuys1iWxNPH4lZ_lrp7n?usp=sharing',
        'https://drive.google.com/drive/folders/1fqITUGSnCof3K3UhLtiPXMwwNAbBZo82?usp=sharing',
        'https://drive.google.com/drive/folders/1Ot2DsLUPFlnLrrIJgpwucs7ITrWw4Prr?usp=sharing',
        'https://drive.google.com/drive/folders/1_qnMmkAgEaOQhBZFGTBnFLQ5hlBkFZ15?usp=sharing',
        'https://drive.google.com/drive/folders/1f2DqbTAw09NbuJL7nQPaBD_1TyjAl3oX?usp=sharing',
        'https://drive.google.com/drive/folders/1J6SinDzP33fUJ9iQ0QCaPvxBZLTImvrg?usp=share_link',
        'https://drive.google.com/drive/folders/1w2aJWkoU0aJLJaxoG8QcWnvEK3lUsauF?usp=share_link',
        'https://drive.google.com/drive/folders/1RJFW-5l4nEurKQUnG1WxrlFG4PLn4qQO?usp=share_link',
        'https://drive.google.com/drive/folders/1O3dAT8dNghduoDuADoeRxddhidTqoVHk?usp=share_link'
    ]
},
{
    title: 'Biology',
    lang: 'EN',
    years: ['One Click', 'Sample Paper', 'Practice Paper', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/13GeQ-dg2YaU_JkYRFzeWgrt0v1ZMqyCr?usp=sharing',
        'https://drive.google.com/drive/folders/1yvHP1pYqfVSLGqp_i_4gwutge3EAKrgG?usp=share_link',
        'https://drive.google.com/drive/folders/1qWtV963pcJPBIOUD5vF6n3a8IS49-Bvk?usp=share_link',
        'https://drive.google.com/drive/folders/1HDT8uv5nnFH6b53kKdyczvhV9wvUxF5l?usp=sharing',
        'https://drive.google.com/drive/folders/16d2tIFhHPTOwlAUwtGJvT0Ni1L50IC08?usp=sharing',
        'https://drive.google.com/drive/folders/1F_vzKIhdBiDUVYCSjOm6BHBVRdO9bCuk?usp=sharing',
        'https://drive.google.com/drive/folders/1IXNpbkI7Htk8dyPmsXtKfN7g0YVAVI68?usp=sharing',
        'https://drive.google.com/drive/folders/1EongY0fUXgNgxfmydUWJ6U5EsFUlYpjZ?usp=sharing',
        'https://drive.google.com/drive/folders/1yEHBedI1OiVJR8sgW0zWIOXull7C_Dm4?usp=sharing',
        'https://drive.google.com/drive/folders/1mqSWfzDUZ0-gOnWiMGD89DzIo_pRkeWy?usp=sharing',
        'https://drive.google.com/drive/folders/1LHelAk3bOb8TXl0GZCUmjiIE6BxFhwaR?usp=sharing',
        'https://drive.google.com/drive/folders/1Kcg65y9n8BPs6Jip7eISs3QrFjPNVuT9?usp=share_link',
        'https://drive.google.com/drive/folders/1yFYfeFL7fp38FBg4QpOu2ftI9hD0mcmC?usp=share_link',
        'https://drive.google.com/drive/folders/1RmO_AidTSufBQBRHt9ng8UQPYoAEzdmC?usp=share_link',
    ]
},
{
    title: '生物',
    lang: 'ZH',
    years: ['One Click', '樣本試卷', '練習試卷', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/1Qii6mjyNJ3myBiv15Q16fWPQZrm_k20J?usp=sharing',
        'https://drive.google.com/drive/folders/1Bgl13pNmEP-tx5EqSGsc9UyrDO7PeTwa?usp=sharing',
        'https://drive.google.com/drive/folders/1unjEXMopwXJjJVzRKYYX9kqoZr-DV40Q?usp=sharing',
        'https://drive.google.com/drive/folders/1g1_abDiPxcMphJARx2_QZrCqb_N8Cxr7?usp=sharing',
        'https://drive.google.com/drive/folders/1fz_nf_-PNcCW4YuSg_ORHhQczY9Nei_3?usp=sharing',
        'https://drive.google.com/drive/folders/1VxJfF5_B4NYPnh8JIlDR-S2KQVwnXNHi?usp=sharing',
        'https://drive.google.com/drive/folders/1ZrPckbbY6n5xNr6DapcVztAU6NJiDvlN?usp=sharing',
        'https://drive.google.com/drive/folders/102bvW8TZt6A5erFyoKdNn2byy1029f3P?usp=sharing',
        'https://drive.google.com/drive/folders/1v24yNpe15a-U_FxgGdzN2RPxRsIjXHtK?usp=sharing',
        'https://drive.google.com/drive/folders/12WV6HYapLWydfIz1HAdFsQiL-aKh4htF?usp=share_link',
        'https://drive.google.com/drive/folders/1Qhy7evCmy2gfw8FvmccO0Xk5P5IMuK1p?usp=share_link',
        'https://drive.google.com/drive/folders/1zVknUoI_E1U6etVI5lstu5QsysIN22YF?usp=share_link',
        'https://drive.google.com/drive/folders/1zLnYk7OmSlccBcK77W21nlQMDj1_n49o?usp=share_link',
        'https://drive.google.com/drive/folders/1d6JNSDRRrEMf8OaFotnUH5X2FEZYeN22?usp=share_link',
    ]
},
{
    title: 'Economy',
    lang: 'EN',
    years: ['One Click', 'Sample Paper', 'Practice Paper', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/1WIYcByp2qNryub7QOjyHsJEkYUBBqEZU?usp=sharing',
        'https://drive.google.com/drive/folders/1KQt4djxwaO521gxYt5e9ungj86V3D0oG?usp=share_link',
        'https://drive.google.com/drive/folders/1js_99aKtJaWcH_HWJGq-A97QjCmwFgmH?usp=share_link',
        'https://drive.google.com/drive/folders/1h-hYTv3qOUXEe-GWSfM8Xx0yxGPCOUN6?usp=sharing',
        'https://drive.google.com/drive/folders/1UdMBh3d7vv2dE4pGw-YlykM9lE9JDDGf?usp=sharing',
        'https://drive.google.com/drive/folders/17e4vJwca1R-yozzRNwN7F6gMl-LpwCor?usp=sharing',
        'https://drive.google.com/drive/folders/1YIB59SIEHmdYJu3MLyXsNnitqVlxteU2?usp=sharing',
        'https://drive.google.com/drive/folders/1lbFbk_afN9t2EjGZpcRNADoCU__9Knd6?usp=sharing',
        'https://drive.google.com/drive/folders/1uNhohAHtgs9_xgvYicF709GbjIt2XqYq?usp=sharing',
        'https://drive.google.com/drive/folders/12lW9TpWjDxAuhtfRrZOZlW-alKmmVqhF?usp=sharing',
        'https://drive.google.com/drive/folders/1MSMPpiMv0q0UA-TbpNqvtOcHsi0_IMGC?usp=sharing',
        'https://drive.google.com/drive/folders/1Iv3_QCvZ-de-LIjmc-nY2MFSZhGChNON?usp=share_link',
        'https://drive.google.com/drive/folders/1ldQ74GXObh-JxFXKrk3R_9gnXMs0WcVd?usp=share_link',
        'https://drive.google.com/drive/folders/1ReAE5nJlQgnBqHqppJP1E-UB5MWeJq0t?usp=share_link',
    ]
},
{
    title: '經濟',
    lang: 'ZH',
    years: ['One Click', '樣本試卷', '練習試卷', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021],
    url: ['https://drive.google.com/drive/folders/1p_N_bwjsghzVrOHDt1-VEpmNuhDxScYi?usp=sharing',
        'https://drive.google.com/drive/folders/1QLE58RplhlL5_CMOB_fFbowpJvBTglr9?usp=sharing',
        'https://drive.google.com/drive/folders/1F3LGPwKFne9wX00AKKxzwgE4hCD3SLDU?usp=sharing',
        'https://drive.google.com/drive/folders/1f8EgTRiFRovbuJutpXKGb58HEzOoW_9J?usp=sharing',
        'https://drive.google.com/drive/folders/11JWXeY2YEY550BCDdUqbievk70ixfqnz?usp=sharing',
        'https://drive.google.com/drive/folders/1ct7cyrZ3E6ywlx2EmDBdGINjbhR8pJNw?usp=sharing',
        'https://drive.google.com/drive/folders/14W6MmAHOrbYLcJdQSTsT-flnn6CouGA4?usp=sharing',
        'https://drive.google.com/drive/folders/1VLuehmVKHGm11ab-ARJ0ekSyMidNm6Ly?usp=sharing',
        'https://drive.google.com/drive/folders/1XSDgKNOlzh-SnSmzpBMXqM8YeHLygNXn?usp=sharing',
        'https://drive.google.com/drive/folders/1xxVTBXPowOQdRPIRGqS34-lg270H6HjJ?usp=share_link',
        'https://drive.google.com/drive/folders/1DCnYrp47AMAsM_Lj1dGjAPOpwCc3zll6?usp=share_link',
        'https://drive.google.com/drive/folders/1fVM1Kgv4jMMUi-Oa4j7Pf1WW8_WDYYt-?usp=share_link',
        'https://drive.google.com/drive/folders/1UzP3Gbu1VU55XXKPfwef0vxCYvoK7RCK?usp=share_link',
    ]
},
{
    title: 'BAFS',
    lang: 'EN',
    years: ['One Click', 'Sample Paper', 'Practice Paper', 2012, 2013, 2014, 2015, 2016, 2017, 2019],
    url: ['https://drive.google.com/drive/folders/1pq2hcw39yYPMaFvLPiEgGN4lwVgf71ef?usp=sharing',
        'https://drive.google.com/drive/folders/1pP2lMcZtqGUPa1EnEk5b6iyJ4HimEx_C?usp=sharing',
        'https://drive.google.com/drive/folders/1eiU3mGAKgbumDy6JcMFQWN4CRCeMObXD?usp=sharing',
        'https://drive.google.com/drive/folders/1uGci5cKAG_E7x3YFETSdg7Zj9DRnOi4L?usp=sharing',
        'https://drive.google.com/drive/folders/1Y7HDJ5FdOq_1WsRoFD-Sj8oJtjD5X9kw?usp=sharing',
        'https://drive.google.com/drive/folders/14a_L3Y2I0ZrxemnelpSebxa50yLCAu-4?usp=sharing',
        'https://drive.google.com/drive/folders/1jJMsYGXmFkG4fkFGghJuA88nxjfYvIo0?usp=sharing',
        'https://drive.google.com/drive/folders/1RFeo1RpiYqISBHDo0CYVEASO8rc836ib?usp=sharing',
        'https://drive.google.com/drive/folders/1nYueRQMKVwal9ZlncR1ZqyFlIlqQ2ET6?usp=sharing',
        'https://drive.google.com/drive/folders/1uekDEM00IrgQuq-M4edDTHAGZNArq_Ix?usp=sharing'

    ]
},
{
    title: 'ICT',
    lang: 'EN',
    years: ['One Click', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/1vB9icXM81Mwi6f1hMZCxzijrAPWGowxp?usp=sharing',
        'https://drive.google.com/drive/folders/1pwLx1hot9TatpUyeW9fi0iU7iRpwll-_?usp=sharing',
        'https://drive.google.com/drive/folders/1-iBmWxtFAnlo4pli6B0H3TxRvp__hEil?usp=sharing',
        'https://drive.google.com/drive/folders/1G8ZOUYZNWOW3fF-8Ds9VGQGH1OgnhgC6?usp=sharing',
        'https://drive.google.com/drive/folders/18UJENYLe6BuYLWOhmniCQPcI1znNI05z?usp=sharing',
        'https://drive.google.com/drive/folders/1eEV9YrIeh-droJA_sS0zKaVjlHUhpzZ2?usp=sharing',
        'https://drive.google.com/drive/folders/1GGHBolDQMhElMTAkCaTR_PdK_2MAhlhX?usp=share_link',
        'https://drive.google.com/drive/folders/1oUR5PBsYXpvKTKZOZYHiPA8DjJfLTCJ9?usp=sharing',
        'https://drive.google.com/drive/folders/1eUayCv211-D1zLwz2YCxHpj22lnPa5mX?usp=sharing',
        'https://drive.google.com/drive/folders/13djJWbbk5mRVogSpsjt_8RvchiExQylR?usp=share_link',
        'https://drive.google.com/drive/folders/1_WnYGTCu4GHtllMzbDDj-Gd_BBPlUvrw?usp=share_link',
        'https://drive.google.com/drive/folders/1HWa1bpwR7nbqZ-4lEX4qPk9a-RyQJbln?usp=share_link',
    ]
},
{
    title: '資訊及通訊科技',
    lang: 'ZH',
    years: ['One Click', '樣本試卷', '練習試卷', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/15bd4CZZGimrGBsDLMs-_bvwo9A1mKqwL?usp=sharing',
        'https://drive.google.com/drive/folders/1TL6-7qeBeqlDvDku95ggSAVljE4w3_HH?usp=sharing',
        'https://drive.google.com/drive/folders/19Gie_yjZ1ZB5LdRfUXiSbh6jH6SqnpIx?usp=sharing',
        'https://drive.google.com/drive/folders/1aCSyirW6oV8lsUuFOLyoG3jFUyd_uTxL?usp=sharing',
        'https://drive.google.com/drive/folders/1yMihoNvcmn2JVeKiSe49eRgiP6HRQa3_?usp=sharing',
        'https://drive.google.com/drive/folders/1KRJxgZ5DEczRDAO09uSO_R5CZ9n1SVK5?usp=sharing',
        'https://drive.google.com/drive/folders/19J3N5h1h7CVoAskpZ_wBkoEkj4oNgLK4?usp=sharing',
        'https://drive.google.com/drive/folders/12gpCPqAA0Uu7LSC_dEEgEq3ZgdNY6CsT?usp=sharing',
        'https://drive.google.com/drive/folders/1CKFs6LOD7_0eDEaU-NhOhgBJPcmJL8JI?usp=sharing',
        'https://drive.google.com/drive/folders/1sAoDXE37mIMM4bgKyomIxoqf1st36EKU?usp=share_link',
        'https://drive.google.com/drive/folders/17Lrw2vQteiurBYbta00b3Tn4XCgsFHXk?usp=share_link',
        'https://drive.google.com/drive/folders/1hDifi4S42h9OUQJT_8i0lG0e-AZEtoG9?usp=share_link',
        'https://drive.google.com/drive/folders/1hiKj0SgEAc3IK12M6zMGQ1155s4wuheP?usp=share_link',
        'https://drive.google.com/drive/folders/1tpvtWurzlARTUn3os9dLi6UVpE25WZbT?usp=share_link',
    ]
},
{
    title: 'Geography',
    lang: 'EN',
    years: ['One Click', 'Sample Paper', 'Practice Paper', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021],
    url: ['https://drive.google.com/drive/folders/1qUlwZtOFGZuE3uCWdZi03tj3rDBMd61N?usp=sharing',
        'https://drive.google.com/drive/folders/1pnkesC_olFF3xeNxaGT1AZl2zacs8h7h?usp=share_link',
        'https://drive.google.com/drive/folders/1nx9xAR3DaCDJhOfABjagGs-orE2WX5Pi?usp=share_link',
        'https://drive.google.com/drive/folders/1HzAMFN9jZh49YEVrVS7CtKZGfeeXxakt?usp=share_link',
        'https://drive.google.com/drive/folders/1QkIKpsNFYIsBItyDvzUPqGxfDCemluTv?usp=share_link',
        'https://drive.google.com/drive/folders/11UUwPW4LeEE096ipE-ZKuYk4drPoln07?usp=share_link',
        'https://drive.google.com/drive/folders/1wreRCPL71lY1YQIUQ_e05hPdYlP9nPqu?usp=share_link',
        'https://drive.google.com/drive/folders/1gNwRgfAAbVJbRve3u8whUwekejR4QV8T?usp=share_link',
        'https://drive.google.com/drive/folders/1NSw-XXVEoH0ZlWlTJUsQ2Pi9darVYlaP?usp=share_link',
        'https://drive.google.com/drive/folders/1gQM7MXIz4KF2MKLNBZvWBqhKzP_Ffco0?usp=share_link',
        'https://drive.google.com/drive/folders/16mR21peDWXpA8I7Pocd737snM8jLqT4k?usp=share_link',
        'https://drive.google.com/drive/folders/1eiivcLrbUotsbM0PeQfpAioLHQ2oq6Tf?usp=share_link',
        'https://drive.google.com/drive/folders/1CTNlstW65UpL7ZirgDd6494OlmxgxQ2X?usp=share_link',
    ]
},
{
    title: '地理',
    lang: 'ZH',
    years: ['One Click', '樣本試卷', '練習試卷', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/1wbYdkE5iezk6Z9F7DPfxybNt86FPNgDI?usp=sharing',
        'https://drive.google.com/drive/folders/17Z9T3J69e2HWJYSQRWlw3BS1vS1ZYEu7?usp=sharing',
        'https://drive.google.com/drive/folders/1uzeWCLGn9Yzq-KdpzrcWO5GCQiVCQqMA?usp=sharing',
        'https://drive.google.com/drive/folders/1dBCp9zuX0tPTwuNpMCCSUdoszjswKx-4?usp=sharing',
        'https://drive.google.com/drive/folders/1Bc3wVRNzH-uORLBaZLnYqjvOaBaiCZO-?usp=sharing',
        'https://drive.google.com/drive/folders/1VKxwXTyXk71utNlFr-2e1zf6h9WAxf0U?usp=sharing',
        'https://drive.google.com/drive/folders/1qJkW7DdFnlOOtzcX87d6ogRLSvHpIaXZ?usp=sharing',
        'https://drive.google.com/drive/folders/1-lpP4_IREKZp0D3X3jUjxzuO2-EsQRMO?usp=sharing',
        'https://drive.google.com/drive/folders/1Vq1OWsGfn88wm1ZYcVcy2-0553MC0XVG?usp=sharing',
        'https://drive.google.com/drive/folders/1GUcuq_E0OrIWSApFa_KrWlDUUDYXmapT?usp=share_link',
        'https://drive.google.com/drive/folders/1IIfNmuXzjFfEcxL26PoIiSl590Fz0DsQ?usp=share_link',
        'https://drive.google.com/drive/folders/1Q8BUp2lY5WxJsIMLvyTuz1fxf1Y9LagU?usp=share_link',
        'https://drive.google.com/drive/folders/1Z0YYCCQZDroT3ApnOSeR0hS-_aUnC3Ov?usp=share_link',
        'https://drive.google.com/drive/folders/14NLq4Zh9gSE3JdcqBPuUEw_tHWi2Vcyz?usp=share_link',
    ]
},
{
    title: '中國歷史',
    lang: 'ZH',
    years: ['One Click', '樣本試卷', '練習試卷', 2012, 2013, 2014, 2015, 2016, 2017, 2019, 2020, 2021],
    url: ['https://drive.google.com/drive/folders/1YC0m395Hr5tUCn9qXOJ-l9dqTR-V60t8?usp=sharing',
        'https://drive.google.com/drive/folders/16NIk7Knf9ygYOKm5XcFBwx73pyVFDGDF?usp=sharing',
        'https://drive.google.com/drive/folders/1Hun12_CAXRrQe096uspLc4Htgc0ckNW7?usp=sharing',
        'https://drive.google.com/drive/folders/1OC7S41kKS0LP14AOTQIBVQcUHaBVcgFh?usp=sharing',
        'https://drive.google.com/drive/folders/141GMu47KZpXCZs8OIPArLylgmoQPNs5O?usp=sharing',
        'https://drive.google.com/drive/folders/12WDzg2WSw2YVAjDAhnbyF7PGdb13DQVS?usp=sharing',
        'https://drive.google.com/drive/folders/1fP2hwqVL89GndPKyhBx5W3dYqMSbhYpY?usp=sharing',
        'https://drive.google.com/drive/folders/1zyRb_B_BPMBZFWiSKZgUWYnjII51sr7o?usp=sharing',
        'https://drive.google.com/drive/folders/1L773AGXkvwSgI9oy7NWEBJif4zXeQNpf?usp=sharing',
        'https://drive.google.com/drive/folders/1Nf2BJzMdQBk0GngiT4Qw4QpKblz1clAO?usp=sharing',
        'https://drive.google.com/drive/folders/1_kcPvvgXRT8QcdSwIm9C84lXu3AAL6kh?usp=share_link',
        'https://drive.google.com/drive/folders/1T7Qae5E66Mwx650b1Qsg5RPxTrfFYbPj?usp=sharing'
    ]
},
{
    title: '中國文學',
    lang: 'ZH',
    years: ['One Click', '樣本試卷'],
    url: [
        'https://drive.google.com/drive/folders/1l2SlrHHpHtc_gJ4mDAviDisp0JFARFON?usp=share_link',
        'https://drive.google.com/drive/folders/1zGUKewADIdk72uH2IuRY0f3NHNJJEKW-?usp=share_link',
    ]
},
{
    title: 'History',
    lang: 'EN',
    years: ['One Click', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021],
    url: ['https://drive.google.com/drive/folders/1JBsy-8b7UOw7WQkpW6CSAK95tUsOQquB?usp=sharing',
        'https://drive.google.com/drive/folders/1IwOn_AqL9KfG2ZPR1ZIgIb356PmHnkXL?usp=sharing',
        'https://drive.google.com/drive/folders/1Zt0gGL4I5sSWJe6HhDH96tsnfcW-6Vju?usp=sharing',
        'https://drive.google.com/drive/folders/1_nP3RzSyG5K86G6dx6PbbCF_qyDvxqhC?usp=sharing',
        'https://drive.google.com/drive/folders/12VQFCc3eHv6kF-bCddoMXs0DYpmogwrr?usp=sharing',
        'https://drive.google.com/drive/folders/1Q36QVZ0CYc8O8NFtNDh6HEJjG8PPn-Uk?usp=sharing',
        'https://drive.google.com/drive/folders/1p9xyAnOeFJJzszNZQnBCpp9ZHE2nvhdL?usp=sharing',
        'https://drive.google.com/drive/folders/1Bc_Zs-2OJa9iChcd2OgMsC8GjcVbFTpv?usp=share_link',
        'https://drive.google.com/drive/folders/1ppQKSffmy-AoGGtD7Wmaa2OjSwIIZo9o?usp=share_link',
        'https://drive.google.com/drive/folders/1NLOe6L4hQQd9oYeJSCOssDeIonM64JlG?usp=share_link',
        'https://drive.google.com/drive/folders/1WvpuOWx6_wpDoeLCoH9zA4kBDJCF1Y08?usp=share_link',
    ]
},
{
    title: '世界歷史',
    lang: 'ZH',
    years: ['One Click', '樣本試卷', '練習試卷', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021],
    url: [
        'https://drive.google.com/drive/folders/1XUU8XWx4QZdKYTiaPXB6hxPx7AzReyIO?usp=share_link',
        'https://drive.google.com/drive/folders/1UQ1gvC5hcTnB9vIUMbW2IwYwm_6ei9S4?usp=share_link',
        'https://drive.google.com/drive/folders/1FEO1XGRXxzg0CMSQQPCOLBwmLQN2savr?usp=share_link',
        'https://drive.google.com/drive/folders/12VCmiaY3s69sdgatY1y_yzG95R0Fj3J_?usp=share_link',
        'https://drive.google.com/drive/folders/1ewDdyz1-d2EaJlExq0Z_ZayCbyzfEGX-?usp=share_link',
        'https://drive.google.com/drive/folders/14xcDDjnOj5togC-fjO2KGM1dIkq_b_D_?usp=share_link',
        'https://drive.google.com/drive/folders/11Aj7FtWeKCaZMtb0Dba5NLELPU4EzD0Q?usp=share_link',
        'https://drive.google.com/drive/folders/1baYOwrE4n4P4SPl-xJBUfco3r-XQeCAG?usp=share_link',
        'https://drive.google.com/drive/folders/1VKruj0d-xbF4znlMItO9Iyfbmw1RiAw5?usp=share_link',
        'https://drive.google.com/drive/folders/1hdLQs46tuyIiLFcyKH6-BZcfEfRj-H5g?usp=share_link',
        'https://drive.google.com/drive/folders/1zTED8D7Qpk7UdYyzlbLRN5s1gIFahc4-?usp=share_link',
        'https://drive.google.com/drive/folders/1aHc1v2wlTVSQox4Y4575ygFIl95DuCkz?usp=share_link',
        'https://drive.google.com/drive/folders/1-ELuxk7qSrOUdS8RJpeO8TVMxtY_0Kne?usp=share_link',
    ]
},
{
    title: 'M1',
    lang: 'EN',
    years: ['One Click', 'Sample Paper', 'Practice Paper', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/11EpOTBeh05bSY8gJ_XqwY6jr4t2Yf-wB?usp=sharing',
        'https://drive.google.com/drive/folders/1zHbMKxe9bpOWvMQRpfR-6gHE1WxIZCsy?usp=sharing',
        'https://drive.google.com/drive/folders/1SphQZZn6Z742Z19TKeP8LPD9ljj0OgXm?usp=sharing',
        'https://drive.google.com/drive/folders/15iUqzA43QsIbF-jcZAQI0eylhzcS_NFQ?usp=sharing',
        'https://drive.google.com/drive/folders/1gYQnwghQb-fgDD29I2h-SDiBF5HADOws?usp=sharing',
        'https://drive.google.com/drive/folders/1cSjvSO5LpVm59m8V-ULXEKcmHnyyHCwJ?usp=sharing',
        'https://drive.google.com/drive/folders/1qL6a-j1ha_MlaeqY0ZpZS7JIFLDljhmm?usp=sharing',
        'https://drive.google.com/drive/folders/1AAhhO77qnKaor9T8VxnpMIYJXiylDW0o?usp=sharing',
        'https://drive.google.com/drive/folders/1ZmAvQZNZLPr08MB9iUYpzW8Sbnebo4_J?usp=sharing',
        'https://drive.google.com/drive/folders/1ZmAvQZNZLPr08MB9iUYpzW8Sbnebo4_J?usp=sharing',
        'https://drive.google.com/drive/folders/1qPDequ0Wsdy-vHZBDDYUr7oh4wIbIeGk?usp=sharing',
        'https://drive.google.com/drive/folders/1iUVXqfp-39fP8W5OdkcL_8rPZxbClLj7?usp=sharing',
        'https://drive.google.com/drive/folders/1RAPByHuMvC-y4zkA6pUuUY6hN2vc1G9g?usp=share_link',
        'https://drive.google.com/drive/folders/1l1H-P59ssl-S_rq5g1lr52dFo1h6JeL6?usp=share_link',
    ]
},
{
    title: 'M2',
    lang: 'EN',
    years: ['One Click', 'Sample Paper', 'Practice Paper', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    url: ['https://drive.google.com/drive/folders/1lN_9ZxkZMXg4iC16xLEHugGnUfZsXZv8?usp=sharing',
        'https://drive.google.com/drive/folders/1pPWgnvSO4oEJgIf98LyG8KVrSpQLoWqK?usp=sharing',
        'https://drive.google.com/drive/folders/1nJ1J17J517xyf0oGW1jK3MOtIPC_0Sa9?usp=sharing',
        'https://drive.google.com/drive/folders/1OAP3G7L9k9Zda7XhKrhUtaehcHINSeDz?usp=sharing',
        'https://drive.google.com/drive/folders/1HISF6slQ1zn0yXcHcLPZs50OMx2C3cWt?usp=sharing',
        'https://drive.google.com/drive/folders/13Ps3nFr3i5dkXIZ9sFK5m1JoTLk1d7uS?usp=sharing',
        'https://drive.google.com/drive/folders/18FztcfTBTaSfHoPmUiHi_j6B0UMmZR1g?usp=sharing',
        'https://drive.google.com/drive/folders/13RS7hjBAKI-q0et_8I4Kr4Nj_gjCRX9s?usp=sharing',
        'https://drive.google.com/drive/folders/1DMeIS2j0sltLMA0Hm1FQQ3NuaELgVVwA?usp=sharing',
        'https://drive.google.com/drive/folders/1mqvYODzlDpNmWNI_MmqMyGVY_UNFSyb3?usp=sharing',
        'https://drive.google.com/drive/folders/1oVg1jOZbQad_Lp8XKcbPNB5WMmMbiokJ?usp=sharing',
        'https://drive.google.com/drive/folders/1b4qHT-P8w_i-1VOZqeGyIhzTogXB_E2R?usp=share_link',
        'https://drive.google.com/drive/folders/109kmoqwXmyBtelMVpEfpWCmpnSPPw130?usp=share_link',
        'https://drive.google.com/drive/folders/1R-pr0z7uzX0ocH3z2kt47VQM-7Sf7lOj?usp=share_link',
    ]
},
]